project_id = "hzgaflrabmrcsokhoatv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
import_path = "./storage"

[auth]
enabled = true
port = 54325
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://students-tracker.vercel.app", "http://localhost:4173"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false
enable_manual_linking = true
minimum_password_length = 6
password_requirements = "letters_digits"

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.external.google]
enabled = false

[auth.external.github]
enabled = false
